;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s -all --nominal -S -o - | filecheck %s

(module
  (type $foo (struct i32))
  (type $bar (struct i32))

  (global $foo.rtt (rtt $foo) (rtt.canon $foo))
  (global $bar.rtt (rtt $bar) (rtt.sub $bar (global.get $foo.rtt)))

  ;; CHECK:      (func $ret-foo (result (ref null $foo))
  ;; CHECK-NEXT:  (struct.new_with_rtt $bar
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:   (global.get $bar.rtt)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $ret-foo (result (ref null $foo))
    (struct.new_with_rtt $bar
      (i32.const 42)
      (global.get $bar.rtt)
    )
  )
)
