;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt %s -all -o %t.text.wast -g -S
;; RUN: wasm-as %s -all -g -o %t.wasm
;; RUN: wasm-dis %t.wasm -all -o %t.bin.wast
;; RUN: wasm-as %s -all -o %t.nodebug.wasm
;; RUN: wasm-dis %t.nodebug.wasm -all -o %t.bin.nodebug.wast
;; RUN: cat %t.text.wast | filecheck %s --check-prefix=CHECK-TEXT
;; RUN: cat %t.bin.wast | filecheck %s --check-prefix=CHECK-BIN
;; RUN: cat %t.bin.nodebug.wast | filecheck %s --check-prefix=CHECK-BIN-NODEBUG

(module
  (rec
    ;; CHECK-TEXT:      (rec
    ;; CHECK-TEXT-NEXT:  (type $a (struct (field (ref null (exact $struct.0))) (field (ref (exact $struct.1)))))
    ;; CHECK-BIN:      (rec
    ;; CHECK-BIN-NEXT:  (type $a (struct (field (ref null (exact $struct.0))) (field (ref (exact $struct.1)))))
    (type $a (struct (field (ref null (exact 0)) (ref (exact 1)))))
    ;; CHECK-TEXT:       (type $b (struct (field (ref (exact $struct.0))) (field (ref null (exact $struct.1)))))
    ;; CHECK-BIN:       (type $b (struct (field (ref (exact $struct.0))) (field (ref null (exact $struct.1)))))
    (type $b (struct (field (ref (exact $a)) (ref null (exact $b)))))
  )

  ;; CHECK-TEXT:      (func $foo (type $2) (param $0 (ref null (exact $struct.0))) (param $1 (ref (exact $struct.1))) (result (ref (exact $struct.0)) (ref null (exact $struct.1)))
  ;; CHECK-TEXT-NEXT:  (local $2 (ref null (exact $struct.0)))
  ;; CHECK-TEXT-NEXT:  (unreachable)
  ;; CHECK-TEXT-NEXT: )
  ;; CHECK-BIN:      (func $foo (type $2) (param $0 (ref null (exact $struct.0))) (param $1 (ref (exact $struct.1))) (result (ref (exact $struct.0)) (ref null (exact $struct.1)))
  ;; CHECK-BIN-NEXT:  (local $2 (ref null (exact $struct.0)))
  ;; CHECK-BIN-NEXT:  (unreachable)
  ;; CHECK-BIN-NEXT: )
  (func $foo (param (ref null (exact $a)) (ref (exact $b)))
             (result (ref (exact $a)) (ref null (exact $b)))
    (local (ref null (exact $a)))
    (unreachable)
  )
)
