;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: wasm-opt %s -all -o %t.text.wast -g -S
;; RUN: wasm-as %s -all -g -o %t.wasm
;; RUN: wasm-dis %t.wasm -all -o %t.bin.wast
;; RUN: wasm-as %s -all -o %t.nodebug.wasm
;; RUN: wasm-dis %t.nodebug.wasm -all -o %t.bin.nodebug.wast
;; RUN: cat %t.text.wast | filecheck %s --check-prefix=CHECK-TEXT
;; RUN: cat %t.bin.wast | filecheck %s --check-prefix=CHECK-BIN
;; RUN: cat %t.bin.nodebug.wast | filecheck %s --check-prefix=CHECK-BIN-NODEBUG

(module
 ;; CHECK-TEXT:      (type $0 (func (param i64 i64) (result i64 i64)))

 ;; CHECK-TEXT:      (type $1 (func (param i64 i64 i64 i64) (result i64 i64)))

 ;; CHECK-TEXT:      (type $2 (func (param i64 i64 i64) (result i64 i64)))

 ;; CHECK-TEXT:      (func $add_wide2 (type $0) (param $x i64) (param $y i64) (result i64 i64)
 ;; CHECK-TEXT-NEXT:  (i64.add_wide2
 ;; CHECK-TEXT-NEXT:   (local.get $x)
 ;; CHECK-TEXT-NEXT:   (local.get $y)
 ;; CHECK-TEXT-NEXT:  )
 ;; CHECK-TEXT-NEXT: )
 ;; CHECK-BIN:      (type $0 (func (param i64 i64) (result i64 i64)))

 ;; CHECK-BIN:      (type $1 (func (param i64 i64 i64 i64) (result i64 i64)))

 ;; CHECK-BIN:      (type $2 (func (param i64 i64 i64) (result i64 i64)))

 ;; CHECK-BIN:      (func $add_wide2 (type $0) (param $x i64) (param $y i64) (result i64 i64)
 ;; CHECK-BIN-NEXT:  (i64.add_wide2
 ;; CHECK-BIN-NEXT:   (local.get $x)
 ;; CHECK-BIN-NEXT:   (local.get $y)
 ;; CHECK-BIN-NEXT:  )
 ;; CHECK-BIN-NEXT: )
 (func $add_wide2 (param $x i64) (param $y i64) (result i64 i64)
  (i64.add_wide2
   (local.get $x)
   (local.get $y)
  )
 )

 ;; CHECK-TEXT:      (func $add_wide3 (type $2) (param $x i64) (param $y i64) (param $z i64) (result i64 i64)
 ;; CHECK-TEXT-NEXT:  (i64.add_wide3
 ;; CHECK-TEXT-NEXT:   (local.get $x)
 ;; CHECK-TEXT-NEXT:   (local.get $y)
 ;; CHECK-TEXT-NEXT:   (local.get $z)
 ;; CHECK-TEXT-NEXT:  )
 ;; CHECK-TEXT-NEXT: )
 ;; CHECK-BIN:      (func $add_wide3 (type $2) (param $x i64) (param $y i64) (param $z i64) (result i64 i64)
 ;; CHECK-BIN-NEXT:  (i64.add_wide3
 ;; CHECK-BIN-NEXT:   (local.get $x)
 ;; CHECK-BIN-NEXT:   (local.get $y)
 ;; CHECK-BIN-NEXT:   (local.get $z)
 ;; CHECK-BIN-NEXT:  )
 ;; CHECK-BIN-NEXT: )
 (func $add_wide3 (param $x i64) (param $y i64) (param $z i64) (result i64 i64)
  (i64.add_wide3
   (local.get $x)
   (local.get $y)
   (local.get $z)
  )
 )

 ;; CHECK-TEXT:      (func $add128 (type $1) (param $a i64) (param $b i64) (param $c i64) (param $d i64) (result i64 i64)
 ;; CHECK-TEXT-NEXT:  (i64.add128
 ;; CHECK-TEXT-NEXT:   (local.get $a)
 ;; CHECK-TEXT-NEXT:   (local.get $b)
 ;; CHECK-TEXT-NEXT:   (local.get $c)
 ;; CHECK-TEXT-NEXT:   (local.get $d)
 ;; CHECK-TEXT-NEXT:  )
 ;; CHECK-TEXT-NEXT: )
 ;; CHECK-BIN:      (func $add128 (type $1) (param $a i64) (param $b i64) (param $c i64) (param $d i64) (result i64 i64)
 ;; CHECK-BIN-NEXT:  (i64.add128
 ;; CHECK-BIN-NEXT:   (local.get $a)
 ;; CHECK-BIN-NEXT:   (local.get $b)
 ;; CHECK-BIN-NEXT:   (local.get $c)
 ;; CHECK-BIN-NEXT:   (local.get $d)
 ;; CHECK-BIN-NEXT:  )
 ;; CHECK-BIN-NEXT: )
 (func $add128 (param $a i64) (param $b i64) (param $c i64) (param $d i64) (result i64 i64)
  (i64.add128
   (local.get $a)
   (local.get $b)
   (local.get $c)
   (local.get $d)
  )
 )

 ;; CHECK-TEXT:      (func $sub128 (type $1) (param $a i64) (param $b i64) (param $c i64) (param $d i64) (result i64 i64)
 ;; CHECK-TEXT-NEXT:  (i64.sub128
 ;; CHECK-TEXT-NEXT:   (local.get $a)
 ;; CHECK-TEXT-NEXT:   (local.get $b)
 ;; CHECK-TEXT-NEXT:   (local.get $c)
 ;; CHECK-TEXT-NEXT:   (local.get $d)
 ;; CHECK-TEXT-NEXT:  )
 ;; CHECK-TEXT-NEXT: )
 ;; CHECK-BIN:      (func $sub128 (type $1) (param $a i64) (param $b i64) (param $c i64) (param $d i64) (result i64 i64)
 ;; CHECK-BIN-NEXT:  (i64.sub128
 ;; CHECK-BIN-NEXT:   (local.get $a)
 ;; CHECK-BIN-NEXT:   (local.get $b)
 ;; CHECK-BIN-NEXT:   (local.get $c)
 ;; CHECK-BIN-NEXT:   (local.get $d)
 ;; CHECK-BIN-NEXT:  )
 ;; CHECK-BIN-NEXT: )
 (func $sub128 (param $a i64) (param $b i64) (param $c i64) (param $d i64) (result i64 i64)
  (i64.sub128
   (local.get $a)
   (local.get $b)
   (local.get $c)
   (local.get $d)
  )
 )

 ;; CHECK-TEXT:      (func $mul_wide_s (type $0) (param $x i64) (param $y i64) (result i64 i64)
 ;; CHECK-TEXT-NEXT:  (i64.mul_wide_s
 ;; CHECK-TEXT-NEXT:   (local.get $x)
 ;; CHECK-TEXT-NEXT:   (local.get $y)
 ;; CHECK-TEXT-NEXT:  )
 ;; CHECK-TEXT-NEXT: )
 ;; CHECK-BIN:      (func $mul_wide_s (type $0) (param $x i64) (param $y i64) (result i64 i64)
 ;; CHECK-BIN-NEXT:  (i64.mul_wide_s
 ;; CHECK-BIN-NEXT:   (local.get $x)
 ;; CHECK-BIN-NEXT:   (local.get $y)
 ;; CHECK-BIN-NEXT:  )
 ;; CHECK-BIN-NEXT: )
 (func $mul_wide_s (param $x i64) (param $y i64) (result i64 i64)
  (i64.mul_wide_s
   (local.get $x)
   (local.get $y)
  )
 )

 ;; CHECK-TEXT:      (func $mul_wide_u (type $0) (param $x i64) (param $y i64) (result i64 i64)
 ;; CHECK-TEXT-NEXT:  (i64.mul_wide_u
 ;; CHECK-TEXT-NEXT:   (local.get $x)
 ;; CHECK-TEXT-NEXT:   (local.get $y)
 ;; CHECK-TEXT-NEXT:  )
 ;; CHECK-TEXT-NEXT: )
 ;; CHECK-BIN:      (func $mul_wide_u (type $0) (param $x i64) (param $y i64) (result i64 i64)
 ;; CHECK-BIN-NEXT:  (i64.mul_wide_u
 ;; CHECK-BIN-NEXT:   (local.get $x)
 ;; CHECK-BIN-NEXT:   (local.get $y)
 ;; CHECK-BIN-NEXT:  )
 ;; CHECK-BIN-NEXT: )
 (func $mul_wide_u (param $x i64) (param $y i64) (result i64 i64)
  (i64.mul_wide_u
   (local.get $x)
   (local.get $y)
  )
 )
)
;; CHECK-BIN-NODEBUG:      (type $0 (func (param i64 i64) (result i64 i64)))

;; CHECK-BIN-NODEBUG:      (type $1 (func (param i64 i64 i64 i64) (result i64 i64)))

;; CHECK-BIN-NODEBUG:      (type $2 (func (param i64 i64 i64) (result i64 i64)))

;; CHECK-BIN-NODEBUG:      (func $0 (type $0) (param $0 i64) (param $1 i64) (result i64 i64)
;; CHECK-BIN-NODEBUG-NEXT:  (i64.add_wide2
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $0)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $1)
;; CHECK-BIN-NODEBUG-NEXT:  )
;; CHECK-BIN-NODEBUG-NEXT: )

;; CHECK-BIN-NODEBUG:      (func $1 (type $2) (param $0 i64) (param $1 i64) (param $2 i64) (result i64 i64)
;; CHECK-BIN-NODEBUG-NEXT:  (i64.add_wide3
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $0)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $1)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $2)
;; CHECK-BIN-NODEBUG-NEXT:  )
;; CHECK-BIN-NODEBUG-NEXT: )

;; CHECK-BIN-NODEBUG:      (func $2 (type $1) (param $0 i64) (param $1 i64) (param $2 i64) (param $3 i64) (result i64 i64)
;; CHECK-BIN-NODEBUG-NEXT:  (i64.add128
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $0)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $1)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $2)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $3)
;; CHECK-BIN-NODEBUG-NEXT:  )
;; CHECK-BIN-NODEBUG-NEXT: )

;; CHECK-BIN-NODEBUG:      (func $3 (type $1) (param $0 i64) (param $1 i64) (param $2 i64) (param $3 i64) (result i64 i64)
;; CHECK-BIN-NODEBUG-NEXT:  (i64.sub128
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $0)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $1)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $2)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $3)
;; CHECK-BIN-NODEBUG-NEXT:  )
;; CHECK-BIN-NODEBUG-NEXT: )

;; CHECK-BIN-NODEBUG:      (func $4 (type $0) (param $0 i64) (param $1 i64) (result i64 i64)
;; CHECK-BIN-NODEBUG-NEXT:  (i64.mul_wide_s
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $0)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $1)
;; CHECK-BIN-NODEBUG-NEXT:  )
;; CHECK-BIN-NODEBUG-NEXT: )

;; CHECK-BIN-NODEBUG:      (func $5 (type $0) (param $0 i64) (param $1 i64) (result i64 i64)
;; CHECK-BIN-NODEBUG-NEXT:  (i64.mul_wide_u
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $0)
;; CHECK-BIN-NODEBUG-NEXT:   (local.get $1)
;; CHECK-BIN-NODEBUG-NEXT:  )
;; CHECK-BIN-NODEBUG-NEXT: )
